### PR TITLE
Update to Architectury 1.18.1

### PR DESCRIPTION
**Pull request by ThexXTURBOXx**
This is still WIP, but features a full upgrade to 1.18.1 together with compatibility for Forge **and Fabric**.

I will update this PR as soon as possible to add the finishing touches.

**Downloads can be found [here](https://github.com/ThexXTURBOXx/ItemTransformHelper/releases) (There are also versions for 1.17.1 and 1.16.5!)**

### CODE REVIEW

**Comment by ThexXTURBOXx** [comment]
Done. This is now ready for review.

This PR is now completely compatible with Forge **and** Fabric.
Feel free to merge this if you want to :)

**Comment by ThexXTURBOXx** [comment]
@TheGreyGhost I added a [1.16.5](https://github.com/ThexXTURBOXx/ItemTransformHelper/tree/1.16.5) and a [1.17.1](https://github.com/ThexXTURBOXx/ItemTransformHelper/tree/1.17.1) backport, both also using Architectury.
Thus, they also feature versions for Fabric **and** Forge.
If you want, you can create branches in your own repo here and let them point to the specific commits :)

I also uploaded releases [here](https://github.com/ThexXTURBOXx/ItemTransformHelper/releases) since your license allows it.
Feel free to do with this PR whatever you want! I am pretty sure that many people wanted an additional Fabric version of this, so here you go! :)

**Comment by TheGreyGhost** [comment]
Thanks dude, I'll review your pull request now, I just need to get my forge and IDE updated, it's been a while...

**Comment by TheGreyGhost** [comment]
Howdy Nico

I've spend a bit of time bringing my build environment up to date and I've run into a couple of snags which means it's going to take a lot longer than I thought.  So in the meantime I'll modify the master readme to redirect people looking for 1.17 or 1.18 to your repo.  As mentioned in the licence I'm more than happy for you to do whatever you like with the code including hosting your own completely independent version.  Thanks for your help with it!

Cheers
  TGG

**Comment by ThexXTURBOXx** [comment]
Hi TGG!
You're more than welcome! :)
If you need help getting something to run on your side, I would also be more than happy to help.
I haven't been using Eclipse for many years now, so I don't know the exact procedure on importing the project there.
I also haven't used VSCode ever to work on Minecraft mods, so I can only guess there as well.
However, I am a frequent user of IntelliJ.
In IDEA, so only need to open the `build.gradle` file as a project and it will automatically work.
~~For me, the `runClient` and `runServer` tasks are not working (I am already in contact with the Architectury authors).~~ (Fixed in newest Architectury Plugin version; had to do with spaces in Windows usernames)
Also, building the mod jars throws errors on remapping the sources. This can be fixed by disabling the source task inside the Gradle files, but the build itself will still finish successfully even when enabled.

I think, this is everything abnormal I could observe.
Cheers
Nico

**Pull request merged**
